### ISSUE TITLE
Old panle api problem

### ISSUE THREAD

**Issue by ehsan-g** [SAY-DAO/panel-legacy#8]
There is a mistype in one of the apis:  (report page)
`https://api.sayapp.company/api/v2/needs?idDone=true&ngoId=3&status=2`

please change idDone to isDone.

**Comment by Elhamne** [comment]
Fixed it.  tnx you saw that!

**Comment by iRhonin** [comment]
@Elhamne Please close the issue when it fixed.

> Fixed it. tnx you saw that!
